### ISSUE TITLE
Usage of binary vs ascii protocol and multigets

### ISSUE THREAD

**Issue by spkrka** [eranharel/memcached-java-clients-benchmark#1] opened 2016-03-17 09:25 UTC
Interesting project! I am just curious why you're using the binary protocol instead of ascii protocol? Ascii seems to perform better in general for multigets.

Also, I think it would be interesting to see benchmark scores for reasonably sized multigets (10-50 items perhaps?)

**Comment by eranharel** [comment] 2016-03-17 10:00
We use the binary protocol cause our past benchmarks and production monitoring showed that it has a much better performance. The main benefit of the text protocol is that it's human readable, and returns the keys in the response which allows you to use tools like Etsy's mctop.

I agree about the multigets performance comment. I'll add that over the weekend if I have time, or you can send a PR.

BTW, @spkrka if you're one of the folsom developers, I'd be very happy to talk to you. One of the reasons I set this up was to compare spymemcached VS folsom, and I was expected the netty based implementation to be more efficient. Since the folsom code is much cleaner than spy's I think it will be easier to optimise, provided the throughput and latency differences are not caused by correctness issues in spy and xmemcached (or over optimistic code if you may).

**Comment by spkrka** [comment] 2016-03-17 10:12
In my experience and tests, binary was much slower and consumed more CPU on the server side. Perhaps I was using a suboptimal version of the memcache server though. It seemed like it would flush after each binary message instead of batching.

Perhaps binary is faster for single gets but ascii is faster for multigets? I mostly tested with multigets since that is the biggest use case for us.

Ascii also transmits less data than binary which reduces overhead.

Yes, I am one of the folsom developers, I just found this project since you made that report recently :)
We have intentionally avoided some of the optimizations that spymemcached does in order to keep the code simple and make sure correctness works (we had some problems with the asyncronous code in spymemcached before), and also because some of the optimizations don't really help in the worst case (grouping together requests for the same key can reduce traffic to memcached, but that can also increase latency and adds code complexity)

I don't have much time this week, but I might make a PR for multiget tests in the future.

Thanks for creating this project, I think it provides useful data!

**Comment by eranharel** [comment] 2016-03-17 10:29
It will be interesting to add the option for binary VS text as well then.

Were you testing against JMemcached or a real memcached server?
JMemcached has a few bugs in the binary protocol implementation. For example the cas operations don't work properly, and I'm not sure about the multiget, but I do remember issues when I was using it in the past.

**Comment by spkrka** [comment] 2016-03-17 10:38
Yes, we only use jmemcached for some of the acceptance tests, but as you say it does not behave the same as a real memcached instance. We were running benchmarks against a real memcached server

**Comment by eranharel** [comment] 2016-03-17 15:18
Added the multi-get + ascii/bianry tests.
I will post the results later - I want to review this commit again, and run it on a quite host.

**Comment by eranharel** [comment] 2016-03-20 15:00
I added the tests and results for binary vs text protocol, and for multi-get of random 50 out of 5000 keys.
The results show that binary multigets perform better, while for get ascii performs better. This may be due to the test setup... not sure.

I had to increase the max outstanding requests quite high cause folsom threw a MemcacheOverloadedException on multigets.

I'm not sure this is the best setup fot the multi-get test. Feel free to review / reopen if you think this needs fixing.

**Closed as completed by eranharel** 2016-03-20 15:00 UTC
